apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .Values.branch }}-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
{{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $.Chart.Name }}-{{ $.Values.branch }}-service
            port:
              number: {{ $.Values.service.port }}
      {{- end }}
{{- end }}
