apiVersion: v2
name: myapp
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: redis
    version: "19.6.1"
    repository: "https://charts.bitnami.com/bitnami"

version: 0.1.21
appVersion: "1.16.21"
