apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.branch }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.branch }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Values.branch }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Values.branch }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ .Chart.Name }}-{{ .Values.branch }}      
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.branch }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"             